version: '3.8'

services:
  migration:
    build:
      context: .
    volumes:
      - .:/django
    env_file:
      - path: .env
        required: true
    command: python manage.py migrate --noinput

  app:
    build: .
    volumes:
      - .:/django
    env_file:
      - path: .env
        required: true
    ports:
      - 8000:8000
    image: app:django
    container_name: my_django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - migration
