version: '3.8'
networks:
  ema_net:
    driver: bridge
services:
  makemigrations:
    build:
      context: .
    volumes:
      - .:/django
    env_file:
      - path: .env
        required: true
    command: python manage.py makemigrations --noinput
    networks:
      - ema_net

  migration:
    build:
      context: .
    volumes:
      - .:/django
    env_file:
      - path: .env
        required: true
    command: python manage.py migrate --noinput
    depends_on:
      - makemigrations
    networks:
      - ema_net

  collectstatic:
    build:
      context: .
    volumes:
      - .:/django
    env_file:
      - path: .env
        required: true
    command: python manage.py collectstatic --noinput
    depends_on:
      - migration
    networks:
      - ema_net

  ema_app:
    build: .
    volumes:
      - .:/django
    env_file:
      - path: .env
        required: true
    ports:
      - 8000:8000
    image: ema-screener:django
    container_name: ema-screener
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - collectstatic
    networks:
      - ema_net
